[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gebru"
version = "1.0.0"
dependencies = [
  "uvicorn",
  "fastapi",
]

[tool.setuptools]
packages = ["src"]
